version: '3.6'

services:
  tip-anywhere-redis:
    image: bitnami/redis:latest
    container_name: tip-anywhere-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASS}
    ports:
      - "6379:6379"