version: '3.6'

networks:
  tip-anywhere-network

services:
  tip-anywhere-redis:
    image: bitnami/redis:latest
    container_name: tip-anywhere-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=${REDIS_PASS}
    ports:
      - "6379:6379"
  tip_anywhere:
    image: postgres
    container_name: tip-anywhere-postgres
    environment: 
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    
    ports: "5432:5432"